library(shiny)
library(shinythemes)
library(rhandsontable)
library(dplyr)

shinyUI(
  tags$div(
    navbarPage(
      title = "RDMLedit",
      theme = shinytheme("cerulean"),
      tabPanel("Files",
               includeMarkdown("md/files.md"),
               fileInput("rdmlFiles",
                         h4("Upload RDML File:"),
                         multiple = TRUE),
               selectizeInput("rdmlFileSlct",
                              "Show File",
                              choices = "",
                              options= list(
                                create =TRUE
                              )),
               selectInput("mergeRdmlsSlct",
                           "Merge RDMLs",
                           multiple = TRUE,
                           choices = ""),
               textInput("dateMadeText", "Date Made",
                         ""),
               textInput("dateUpdatedText", "Date Updated",
                         ""),
               actionButton("removeRDMLBtn",
                            "Remove RDML"),
               actionButton("updateRDMLBtn",
                            "Update"),
               downloadLink("downloadRDML", "Download RDML")),
      navbarMenu("Metadata",
                 tabPanel("ID",
                          selectizeInput("idSlct",
                                         "Select ID",
                                         choices = "",
                                         options= list(
                                           create =TRUE
                                         )),
                          textInput("idPublisherText", "Publisher",
                                    ""),
                          textInput("idSerialNumberText", "Serial Number",
                                    ""),
                          textInput("idMD5HashText", "MD5 Hash",
                                    ""),
                          actionButton("removeIDBtn",
                                       "Remove ID")),
                 tabPanel("Experimenter",
                          selectizeInput("experimenterSlct",
                                         "Select Experiment",
                                         choices = "",
                                         options= list(
                                           create =TRUE
                                         )),
                          
                          textInput("experimenterIdText", "ID",
                                    ""),
                          textInput("experimenterFirstNameText", "First Name",
                                    ""),
                          textInput("experimenterLastNameText", "Last Name",
                                    ""),
                          textInput("experimenterEmailText", "Email",
                                    ""),
                          textInput("experimenterLabNameText", "Lab Name",
                                    ""),
                          textInput("experimenterLabAdressText", "Lab Address",
                                    ""),
                          actionButton("removeExperimenterBtn",
                                       "Remove Experimenter")),
                 tabPanel("Documentation",
                          selectizeInput("documentationSlct",
                                         "Select Documentation",
                                         choices = "",
                                         options= list(
                                           create =TRUE
                                         )),
                          textInput("documentationIdText", "ID",
                                    ""),
                          textInput("documentationTextText", "Text",
                                    ""),
                          actionButton("removeDocumentationBtn",
                                       "Remove Documentation")),
                 tabPanel("Dye",
                          selectizeInput("dyeSlct",
                                         "Select Dye",
                                         choices = "",
                                         options= list(
                                           create =TRUE
                                         )),
                          #                           uiOutput("dyeSlct"),
                          #                           uiOutput("dyeTabWell"),
                          textInput("dyeIdText", "ID",
                                    ""),
                          textInput("dyeDescriptionText", "Text",
                                    ""),
                          actionButton("removeDyeBtn",
                                       "Remove Dye")
                          
                 ),
                 tabPanel("Sample",
                          selectizeInput("sampleSlct",
                                         "Select Sample",
                                         choices = "",
                                         options= list(
                                           create =TRUE
                                         )),
                          textInput("sampleIdText", "ID",
                                    ""),
                          textInput("sampleDescriptionText", 
                                    "Description",
                                    ""),
                          selectInput("sampleDocumentationSlct",
                                      "Documentation",
                                      multiple = TRUE,
                                      choices = ""),
                          wellPanel(selectizeInput("samplexRefSlct",
                                                   "Select xRef",
                                                   choices = "",
                                                   options= list(
                                                     create =TRUE
                                                   )),
                                    textInput("samplexRefNameText", 
                                              "xRef Name",
                                              ""),
                                    textInput("samplexRefIdText", 
                                              "xRef ID",
                                              ""),
                                    actionButton("removeSamplexRefBtn",
                                                 "Remove xRef")),
                          wellPanel(selectizeInput("sampleAnnotationSlct",
                                                   "Select Annotation",
                                                   choices = "",
                                                   options= list(
                                                     create =TRUE
                                                   )),
                                    textInput("sampleAnnotationPropertyText", 
                                              "Annotation Property",
                                              ""),
                                    textInput("sampleAnnotationValueText", 
                                              "Annotation Value",
                                              ""),
                                    actionButton("removeSampleAnnotationBtn",
                                                 "Remove Annotation")),
                          selectInput("sampleTypeSlct",
                                      "Type",
                                      choices = c("unkn", "nac",
                                                  "std", "ntp",
                                                  "nrt", "pos",
                                                  "opt")),
                          checkboxInput("sampleInterRunCalibratorChk",
                                        "Inter Run Calibrator",
                                        FALSE),
                          wellPanel("Quantity",
                                    textInput("sampleQuantityValueText", 
                                              "Value",
                                              ""),
                                    selectInput("sampleQuantityUnitSlct",
                                                "Unit",
                                                choices = c("other",
                                                            "cop", "fold",
                                                            "dil", "ng",
                                                            "nMol"))
                          ),
                          checkboxInput("sampleCalibrationSampleChk",
                                        "Calibartion Sample",
                                        FALSE),
                          wellPanel("cDNA Synthesis Method",
                                    textInput("sampleCsmEnzymeText", 
                                              "Enzyme",
                                              ""),
                                    selectInput("sampleCsmPrimingMethodSlct",
                                                "Priming Method",
                                                choices = c("",
                                                            "oligo-dt", "random",
                                                            "target-specific",
                                                            "oligo-dt and random",
                                                            "other")),
                                    checkboxInput("sampleCsmDnaseTreatmentChk",
                                                  "DNAase Treatment",
                                                  FALSE),
                                    selectInput("sampleCsmTccSlct",
                                                "Thermal Cycling Conditions",
                                                choices = "")
                          ),
                          wellPanel("Template Quantity",
                                    textInput("sampleTemplateQuantityConcText", 
                                              "Concentration",
                                              ""),
                                    selectInput("sampleTemplateQuantityNucleotideSlct",
                                                "Nucleotide",
                                                choices = c("",
                                                            "DNA",
                                                            "genomic DNA",
                                                            "cDNA",
                                                            "RNA"))
                          ),
                          actionButton("removeSampleBtn",
                                       "Remove Sample")),
                 tabPanel("Target",
                          "sfas"),
                 tabPanel("Thermal Cycling Conditions",
                          "sfas")),
      tabPanel("Fluorescence Points")
    ),
    uiOutput("logText")
  )
)
