library(shiny)

shinyUI(fluidPage(
  titlePanel("RDML import"),
  sidebarLayout(
    sidebarPanel(
      fileInput("rdml.file", h4("Upload RDML File:"),
                accept=c("application/zip", ".rdml")),
      h4("Input Options:"),
      textInput("pattern", "Name Pattern:", "%NAME%__%TUBE%"),      
      tags$ul("Possible keys in Name Pattern:",              
              tags$li('%NAME% - name of the sample inputted in the qPCR software (ex.: "Sample 1")'),
              tags$li('%ID% - tube ID (ex.: "23")'),
              tags$li('%TUBE% - tube name (ex.: "B11")'),
              tags$li('%TARGET% - PCR target (ex.: "GAPDH")'),
              tags$li('%TYPE% - type of the sample (ex.: "unkn")')),
      checkboxInput("omit.ntp", "Omit 'ntp' Type Samples", TRUE),
      helpText(" If checked, samples with 'ntp' type (mark for empty sample in data files 
               generated by LightCycler 96 software) are omitted."),
      conditionalPanel(
        condition = "document.getElementById('rdml.file').value != ''",
        actionButton("update", "Update"),
        tags$ul(h4("Download As:"), 
                tags$li(downloadLink("downloadRdmlObj", "RDML_object")),
                tags$li(downloadLink("downloadCsv", "CSV")),
                tags$li(downloadLink("downloadCsvFiltered", "CSV filtered")))
      )
    ),
    mainPanel(
      conditionalPanel(
        condition = "document.getElementById('rdml.file').value == ''",
        h2("Please upload your data first..."),
        img(src="RDML_logo.png", alt = "RDML logo", width="60%", height="60%")
      ),
      conditionalPanel(
        condition = "document.getElementById('rdml.file').value != ''",
        tabsetPanel(
          tabPanel("RDML object summary", verbatimTextOutput('rdml.summary.out')),
          tabPanel("Table/Plots",                 
                   h4("Filter by:"),
                   fluidRow(
                     column(4, uiOutput("ui.targets")),
                     column(4, uiOutput("ui.types")),                                     
                     column(4, textInput("names.filter", "Names:", ""))
                   ),
                   fluidRow(
                     column(3, uiOutput("ui.dtypeSelector")),
                     column(3,radioButtons("tablePlotsSelector",
                                           "View as:",
                                           c("Table" = "table",
                                             "Plots" = "plots"))),
                     conditionalPanel(
                       condition = "input.tablePlotsSelector == 'plots'",
                       column(3,radioButtons("plotStyle",
                                             "Plot Style:",
                                             c("Single" = "single",
                                               "Multi" = "multi"))))
                   ),
                   conditionalPanel(
                     condition = "input.tablePlotsSelector == 'table'",
                     tableOutput("overview.table")
                   ),
                   conditionalPanel(
                     condition = "input.tablePlotsSelector == 'plots'",
                     plotOutput("overview.plot"))
          )
        )
      )
    )
  )
)
)