#' Gets fluorescence data vectors from \code{RDML} object
#' 
#' Gets fluorescence data vectors from \code{RDML} object for specified method
#' of experiment.
#' 
#' @param request Output from AsTable method(\link{RDML.AsTable})
#' @param data.type Type of fluorescence data ('adp' for qPCR or 'mdp' for
#'   melting)
#' @param first.col.name
#' @param long.table Output table is ready for ggplot (See \link{RDML.AsTable}
#'   for example)
#' @return \code{matrix} which contains selected fluorescence data and 
#'   additional information fromm request if \code{long.table = TRUE}.
#' @author Konstantin A. Blagodatskikh <k.blag@@yandex.ru>, Stefan Roediger 
#'   <stefan.roediger@@hs-lausitz.de>, Michal Burdukiewicz 
#'   <michalburdukiewicz@@gmail.com>
#' @references Regular Expressions as used in R -- 
#'   http://stat.ethz.ch/R-manual/R-devel/library/base/html/regex.html
#' @keywords manip
#' @docType methods
#' @name AsDendrogram
#' @aliases RDML.AsDendrogram
#' @rdname asdendrogram-method
#' @include RDML.R
#' @examples 
#' ## internal dataset BioRad_qPCR_melt.rdml (in 'data' directory)
#' ## generated by Bio-Rad CFX96. Contains qPCR and melting data.
#' ## Import without splitting by targets/types and with
#' ## custom name pattern.
#' PATH <- path.package("RDML")
#' filename <- paste(PATH, "/extdata/", "BioRad_qPCR_melt.rdml", sep ="")
#' cfx96 <- RDML$new(filename)
#' ## Select melting fluorescence data with sample.type 'unkn'.
#' library(dplyr)
#' tab <- cfx96$AsTable()
#' fdata <- cfx96$GetFData(filter(tab, sample.type == "unkn"),
#'                         data.type = "mdp")
#' ## Show names for getted fdata
#' names(fdata)
RDML$set("public", "AsDendrogram",
         function(plot.dendrogram = TRUE) {
           
           total.table <- self$AsTable(adp = !all(is.na(data$adp)),
                                       mdp = !all(is.na(data$mdp)))
           tree<-list()
           attributes(tree)<-list(members = 0, height = 5)
           class(tree)<-"dendrogram"
           for(exper.id in unique(total.table$exp.id)) {
             
             tree[[exper.id]] <- list()
             attributes(tree[[exper.id]]) <- list(members = 0,
                                                  height = 4,
                                                  edgetext = exper.id)
             for(r.id in total.table %>% 
                 filter(exp.id == exper.id) %>% 
                 .$run.id %>% unique) {
               tree[[exper.id]][[r.id]] <- list()
               attributes(tree[[exper.id]][[r.id]]) <- 
                 list(members = 0,
                      height = 3,
                      edgetext = r.id)
               for(trgt in total.table %>% 
                   filter(exp.id == exper.id,
                          run.id == r.id) %>% 
                   .$target %>% unique) {
                 tree[[exper.id]][[r.id]][[trgt]] <- list()
                 
                 attributes(tree[[exper.id]][[r.id]][[trgt]]) <- 
                   list(members = 0,
                        height = 2,
                        edgetext = trgt)
                 for(stype in total.table %>% 
                     filter(exp.id == exper.id,
                            run.id == r.id,
                            target == trgt) %>% 
                     .$sample.type %>% unique) {
                   tree[[exper.id]][[r.id]][[trgt]][[stype]] <- list()
                   attributes(tree[[exper.id]][[r.id]][[trgt]][[stype]]) <- 
                     list(members = 0,
                          height = 1,
                          edgetext = stype)
                   for(exp.type in c("adp", "mdp")) {
                     tree[[exper.id]][[r.id]][[trgt]][[stype]][[exp.type]] <- list()
                     n.rows <- total.table %>% 
                       filter(exp.id == exper.id,
                              run.id == r.id,
                              target == trgt,
                              sample.type == stype) %>% 
                       filter_(sprintf("%s == TRUE", exp.type)) %>% 
                       nrow
                     attributes(tree[[exper.id]][[r.id]][[trgt]][[stype]][[exp.type]]) <- 
                       list(members = 1,
                            height = 0,
                            edgetext = exp.type,
                            label = n.rows,
                            leaf = TRUE)
                     
                     attributes(tree[[exper.id]][[r.id]][[trgt]][[stype]])$members <- 
                       attributes(tree[[exper.id]][[r.id]][[trgt]][[stype]])$members + 1
                     
                     attributes(tree[[exper.id]][[r.id]][[trgt]])$members <- 
                       attributes(tree[[exper.id]][[r.id]][[trgt]])$members + 1
                     
                     attributes(tree[[exper.id]][[r.id]])$members <- 
                       attributes(tree[[exper.id]][[r.id]])$members + 1
                     
                     attributes(tree[[exper.id]])$members <- 
                       attributes(tree[[exper.id]])$members + 1
                     
                     attributes(tree)$members <- 
                       attributes(tree)$members + 1
                   }
                 }
               }
             }
           }
           if(plot.dendrogram) {
             suppressWarnings(plot(rev(tree),
                                  center=TRUE,
                                  horiz=TRUE,
                                  yaxt="n"))
             xtick<-seq(0, 5, by=0.5)
             axis(side=1,
                  at=xtick,
                  lty = "blank",
                  las = 2,
                  labels = c("Number\nof samples",
                             "Data type",
                             "",
                             "Sample\ntype",
                             "",
                             "Target\n(gene)",
                             "",
                             "Run ID",
                             "",
                             "Experiment ID",
                             ""))
           }
           return(tree)},
         overwrite = TRUE)