#' Select fluorescence data vectors.
#' 
#' Selects fluorescence data vectors from \code{RDML_object} with specified
#' types, targets and sample names.
#' 
#' If \code{targets = NA}, then use all the available targets from run.\cr If
#' \code{types = NA}, then use all the available types from specified
#' \code{targets}.\cr \code{snames} are really not samples names but columns
#' names generated by \code{RDML name.pattern}. \code{targets} and \code{types}
#' options have higher priority than \code{snames} option. In other words if
#' you specified \code{targets} or \code{types} you can't select samples with
#' other type or target despite specified \code{snames}.\cr
#' 
#' @param object RDML_object.
#' @param melt if TRUE -- use melting data.
#' @param targets run targets to choose from (See 'Details').
#' @param types sample types to choose from (See 'Details').
#' @param snames regular expression to select sample names (See 'Details')
#' @return \code{data.frame} which contains selected fluorescence data
#' \code{vector}s and Cycles/Temperatures in the first column.
#' @section Warning: Resulting \code{data.frame} can contain columns with same
#' names! Use \code{name.pattern} option from \code{RDML} function to avoid
#' this.
#' @author Konstantin A. Blagodatskikh <k.blag@@yandex.ru>, Stefan Roediger
#' <stefan.roediger@@hs-lausitz.de>, Michal Burdukiewicz
#' <michalburdukiewicz@@gmail.com>
#' @references Regular Expressions as used in R --
#' http://stat.ethz.ch/R-manual/R-devel/library/base/html/regex.html
#' @keywords manip
#' @export
#' @examples
#' 
#' 
#' ## EXAMPLE 1:
#' ## internal dataset BioRad_qPCR_melt.rdml (in 'data' directory)
#' ## generated by Bio-Rad CFX96. Contains qPCR and melting data.
#' ## Import without splitting by targets/types and with
#' ## custom name pattern.
#' library(chipPCR)
#' PATH <- path.package("RDML")
#' filename <- paste(PATH, "/extdata/", "BioRad_qPCR_melt.rdml", sep ="")
#' cfx96 <- RDML(filename, 
#'               name.pattern = "%TUBE%_%NAME%_%TYPE%_%TARGET%")
#' ## Select samples with names that contain word 'unkn'.
#' fdata <- selectFData(cfx96, snames="unkn")
#' ## Show names of selected samples
#' names(fdata)
#' ## Use plotCurves function from the chipPCR package to 
#' ## get an overview of the amplification curves
#' plotCurves(fdata[, 1], fdata[, -1])
#' 
#' ## EXAMPLE 2:
#' ## internal dataset lc96_bACTXY.rdml (in 'data' directory)
#' ## generated by Roche LightCycler 96. Contains qPCR data
#' ## with four targets and two types.
#' ## Import with default settings.                     
#' PATH <- path.package("RDML")
#' filename <- paste(PATH, "/extdata/", "lc96_bACTXY.rdml", sep ="")
#' lc96 <- RDML(filename)
#' ## Select samples with targets 'FAM@@bACT' or 'Hex@@X',
#' ## type 'std' and names that contain word 'Sample 39' or 'Sample 4'
#' fdata <- selectFData(lc96, targets=c("FAM@@bACT", "Hex@@X"), types = "std", snames="(Sample 39)|(Sample 4)")
#' ## Show names of selected samples
#' names(fdata)
#' 
selectFData <- function(object,
                        melt = FALSE,
                        targets = NA, 
                        types = NA, 
                        snames = NA) 
  {
  if (class(object) != "RDML_object") stop("object must be of class 'RDML_object'!")
  runtype <- ifelse(melt,
                    "Melt",
                    "qPCR")
  
  # if targets=NA, then all available targets in run
  if (anyNA(targets)) targets <- names(object[[runtype]])
  
  # add first column with cycles ot temperatures
  output <- object[[runtype]][[1]][[1]][1]
  
  for(fluorTarget in targets)
  {
    at.target.types <- names(object[[runtype]][[fluorTarget]])
    at.target.types <- unique(at.target.types)
    # if types=NA, then all available types for current target
    if (is.na(types)) use.types <-  at.target.types
    else use.types <- intersect(at.target.types, types)    
    for(fluorType in use.types)
    {      
      if(is.na(snames)) {      
        output <- cbind(output, object[[runtype]][[fluorTarget]][[fluorType]][-1])
      }
      else {
        cols <- grep(snames, names(object[[runtype]][[fluorTarget]][[fluorType]]))
        cols <- unique(cols)
        output <- cbind(output, object[[runtype]][[fluorTarget]][[fluorType]][cols])
      }
    }
  }
  if (length(output) == 1) return(data.frame())
  return(output)
}
